### PR TITLE
restart support in java bindings

### PR DESCRIPTION
**Pull request by mkurt**
Tried to support restart operation in java.

### CODE REVIEW

**Comment by jadamcrain** [comment]
Looks good.

Have you been able to get this all to compile and verify reception?

**Comment by mkurt** [comment]
there was a mistake when checking warm restart support and it is fixed now. I compiled and tested it on windows.

**Comment by jadamcrain** [comment]
Will get this merged before 2.3.0-RC1.  It looks like the code generator has some non-determinism which causes tons of erroneous diffs.

**Comment by jadamcrain** [comment]
After making the JNI code generator output deterministic, I redid this PR here:

https://github.com/automatak/dnp3/pull/275

**Pull request closed without merging**
