### PR TITLE
Perform event scan on detecting events IIN bit

### PR DESCRIPTION
**Pull request by sidhoda**
Adds configurable behaviour to the master to automatically perform class 1, 2, 3 poll whenever the outstation reports CLASS1_EVENTS, CLASS2_EVENTS, CLASS3_EVENTS IIN bits.

### CODE REVIEW

**Comment by jadamcrain** [comment]
Hi Sid,

The task scheduler has changed pretty drastically internally on the 2.0.x-feature branch.  There is no chance that this feature will merge cleanly with the work done there. Any chance of porting to the feature branch?

-Adam

**Comment by sidhoda** [comment]
Had a quick look at the new task scheduler on the feature branch and shouldn't be too hard to port. I should have some time to do this on Monday.

Is the plan to merge the feature branch after the initial 2.0 release?

Sid

**Comment by jadamcrain** [comment]
Yes, that's the plan. They'll be part of the next minor release.

**Comment by sidhoda** [comment]
Closing pull request, will open new request against 2.0.x-feature branch.

**Pull request closed without merging**
