### PR TITLE
Add *.s and *.ii format to .gitignore file

### PR DESCRIPTION
**Pull request by 3a8r**
Add two format *.s and *.ii to .gitignore file

### CODE REVIEW

**Comment by jadamcrain** [comment]
Hi,

I've no problem merging this, but out of curiosity, why are .s and .ii files being created?

-Adam

**Comment by 3a8r** [comment]
Hi, 
I'm using dnp3 library, in another project, OpenRTU, you can see in my projects. I want to write a make file to build libraries i use, include dnp3. When build libraries finished, i have so many .s and .ii files in my dnp3 folder.

**Comment by blytkerchan** [comment]
Probably the -save-temps option for gcc: very useful for debugging compile-time errors.

rlc

## 

I am Ronald's iPhone and I approve this message (now that I've edited it extensively using autocorrect)

**Comment by 3a8r** [comment]
I don't know. I just have a lot of these files and when i want to commit my own codes, git tell me you have uncommited code in dnp3 folder.

**Comment by jadamcrain** [comment]
Cmake supports out-of-tree builds so that you don't have to worry about black listing every possible build output.

**Comment by blytkerchan** [comment]
I would recommend two things:
1. that Adam merge your patch
2. that you build out-of-tree (e.g. in a .build directory) to avoid mixing source and generated files.

rlc

## 

I am Ronald's iPhone and I approve this message (now that I've edited it extensively using autocorrect)

**Comment by 3a8r** [comment]
Thanks

**Comment by jadamcrain** [comment]
No problem, the existing .gitignore is largely due to our long history with previous build systems like autotools. It's pretty harmless to keep it as is though.

**Pull request merged**
