### PR TITLE
Merge discontiguous point indexes into 2.0.x-feature

### PR DESCRIPTION
**Pull request by atmurray**
Addition of discontiguous point index feature by implementing PointIndexes class that is a collection of contiguous ranges. StaticRange then uses this class to iterate over each of these contiguous ranges when returning ranges of indexes.

Desired indexes are specified when constructing a database by passing a PointIndexes object to DatabaseTemplate (instead of a single integer for the number of points). The DynamicPointIndexes and StaticPointIndexes classes can be used to create the underlying buffer storage used for PointIndexes.

Example modification to Outstation demo which sets each type to have the indexes <3,4,5,6,10,13,17>:

```
    //stackConfig.dbTemplate = DatabaseTemplate::AllTypes(10);
    DynamicPointIndexes indexes({{3,6},10,13,17});
    stackConfig.dbTemplate = DatabaseTemplate(indexes,indexes,indexes,indexes,indexes,indexes,indexes,indexes);
```

All existing tests pass. Additional tests to exercise DNP3 conformance requirements for returning multiple contiguous ranges of indexes via multiple responses added.

### CODE REVIEW

**Comment by jadamcrain** [comment]
Ok, will check this out and get it merged likely the week of the 20th as I have a lot of time in airports.

In the 2.0.x-feature branch there are no longer static/dynamic options for database/buffers.  It shouldn't be necessary to implement the static variants anymore as we're allowing use of malloc/new during intialization.

Thanks Alan.

**Comment by atmurray** [comment]
Great, let me know if you have any issues.

We can probably remove StaticPointIndexes and look at combining
DynamicPointIndexes into PointIndexes.
Also, I noticed you've create a managed pointer class, I could look at
using that for passing in the pointer to the point indexes if you like?

**Comment by jadamcrain** [comment]
I have some time to check it out this afternoon. I'll let you know about the pointers, etc. I don't want to keep kicking this contribution down the road, so let's get it merged and get on the same codebase.

Will you guys be able to use a standard branch once this is merged?

**Comment by jadamcrain** [comment]
Hi Alan,

AVR Studio complains about lack support for std::initializer_list.  In general, the outstation isn't using any C++11 specific headers or STL. These are usable on the master, but not the outstation.

Is there a way to implement this functionality without the use of std::initializer_list?

-AC

**Comment by atmurray** [comment]
Ah, thought that might be the case.
There are two other constructors...

Initialisation using a collection of increasing point indexes:
DynamicPointIndexes(openpal::Indexable<uint32_t, uint32_t> points)

Initialisation using a collection of increasing <start, stop> pairs:
DynamicPointIndexes(openpal::Indexable<Range, uint32_t> pointranges)

We're happy to remove the use of initializer_list, in fact we don't even
use it for our purposes.

In the long run, if we run into other C++11 functionality that would be
nice to have for the outstation, do you think it would be worth having a
collection of wrappers that added such functionality for build environments
that support it? For instance, it would be nice to have a wrapper that
defined the required std::iterator interface for several classes so
niceties such as range based for loops could be used.

Cheers,

Alan

**Comment by jadamcrain** [comment]
Ok, great. Just ping me when you have this updated without the initializer list and I will try to re-merge.

Yes, we can add convenience classes so long as they aren't required to build the outstation. My preference would be to put such adapters in the asiodnp3 project to make it clear it's for full OS platforms.

**Comment by atmurray** [comment]
Have updated accordingly.
However, needed to add resize() functionality to DynamicArray so that PointIndexes are assignable (for when using assignment operator of DatabaseTemplate)
I know this is a kludge, do you have any ideas for a cleaner solution?

**Comment by jadamcrain** [comment]
I just confirmed that everything now compiles under AVR studio.

I am going to merge this now into 2.0.x-feature and start reviewing. I haven't quite yet got my brain wrapped around how it all works just yet, but the additions look clean so let's just proceed.

-Adam

**Comment by jadamcrain** [comment]
BTW, have you made any progress on the other item that we've been discussing (ODC)?

-Adam

**Pull request merged**
