### PR TITLE
Build errors for aarch64-fsl-linux

### PR DESCRIPTION
**Pull request by Vladimir-Ostapchuk**
Fixes aarch64-fsl-linux-g++ (Linaro GCC 4.9-2015.03) 4.9.3 20150311 (prerelease) were added.

### CODE REVIEW

**Comment by jadamcrain** [comment]
I made a change to the CI that should cause it to run on a PR. Can you try closing and opening again?

**Comment by Vladimir-Ostapchuk** [comment]
Hi Adam,

How are you?

Do you mean - close PR and create it again?

--
Best,
Vladimir

**Comment by jadamcrain** [comment]
Yes please. I was hoping it would trigger the build when I edited `ci.yml` but it didn't. If it still doesn't work I'll try creating my own PR using your branch.

**Comment by Vladimir-Ostapchuk** [comment]
Another PR will be created for CI.

**Comment by Vladimir-Ostapchuk** [comment]
Hi Adam,

It did not pass [image: @github-actions]
<https://github.com/apps/github-actions>
CI / conformance (pull_request).
Is it something I need to fix?

**Comment by jadamcrain** [comment]
The failure was unrelated to the C++ build. There are some issues w/ the CI but given that project is approaching EOL in September I'm not going to worry about it. I just wanted to ensure that the 3 main compilers were happy with the change.

**Comment by jadamcrain** [comment]
I'll do a final release w/ this and any other patches just before the EOL. thanks.

**Pull request merged**
