### PR TITLE
Fixed always INVALID timestamp for group 13/43

### PR DESCRIPTION
**Pull request by sidhoda**
Noticed this one during testing.
Had a search through the code and couldn't anywhere else I've missed.

### CODE REVIEW

**Comment by jadamcrain** [comment]
Thanks, we should probably try to tie this particular class into the code generator, as it's just "metadata" that we can model there. Would avoid this issue.

**Comment by sidhoda** [comment]
I agree regarding code generator. It would also be useful to expose the TypeHasTimestamp and GetType via C#, perhaps via HeaderInfo. Would it be worth moving both of these methods into global functions (similar to the enum conversion functions) so don't also need to code generate the other methods on GroupVariationRecord?

**Comment by jadamcrain** [comment]
The best way to model this in the code generator is to have required interface methods for each group/variation that provide this info.

Then we can simply loop over all groups/variations to create the lookups we need, whatever they may be.

Let's make a ticket out of this for now and revisit it before we make another release.

**Comment by jadamcrain** [comment]
Added the ticket here:

https://github.com/automatak/dnp3/issues/120

**Pull request merged**
