### PR TITLE
install libraries bat file

### PR DESCRIPTION
**Pull request by pgiu**
Adam, I created this bat file to automatically update my local .lib and .h files after compiling the libraries. After copying that files I can safely link them (because they are at a set folder) and use them in other custom projects. 
I have no idea if it should be on the root folder, but if you move it, some relative paths should be changed.

### CODE REVIEW

**Comment by jadamcrain** [comment]
Doesn't visual studio have an "install" mechanism that puts header and libraries in system defined location?

This is the Windows equivalent of

> sudo make install

**Comment by pgiu** [comment]
I have no idea if there is a default method... It sounds like there should. I'll check that out on the internet.

**Comment by jadamcrain** [comment]
There's a checkbox marked "deploy" under Build -> Configuration manager but I'm not sure what it actually does.

**Comment by pgiu** [comment]
mmmm... interesting. Let's not reinvent the wheel then.

**Pull request closed without merging**
